---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sim.example.local
  resources:
  - networksimulations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sim.example.local
  resources:
  - networksimulations/finalizers
  verbs:
  - update
- apiGroups:
  - sim.example.local
  resources:
  - networksimulations/status
  verbs:
  - get
  - patch
  - update
